services:

  dst_master:
    container_name: dst_master
    image: sunwoo2539/dst-dedicated:v0.1.0
    ports:
      - 10999:10999/udp
    volumes:
      - ./DSTClusterConfig:/home/steam/.klei/DoNotStarveTogether/DSTWhalesCluster
      - ./volumes/mods:/home/steam/server_dst/mods
    environment:
      - SHARD_NAME=Master
    networks:
      - dst_cluster
    stdin_open: true
    tty: true

  dst_caves:
    container_name: dst_caves
    image: sunwoo2539/dst-dedicated:v0.1.0
    ports:
      - 10998:10998/udp
    volumes:
      - ./DSTClusterConfig:/home/dst/.klei/DoNotStarveTogether/DSTWhalesCluster
      - ./volumes/mods:/home/dst/server_dst/mods
    environment:
      - SHARD_NAME=Caves
    networks:
      - dst_cluster
    links:
      - dst_master

networks:
  dst_cluster:
